### ISSUE TITLE
What is danger_map?

### ISSUE THREAD

**Issue by minty99** [COVIDAnalytics/DELPHI#21]
I tried to run the python scripts, but it can't find danger_map data. I already read the documentation.

Where can I download it? I think some files are omitted and the paths provided in `config.yml` is not correct for run.

**Comment by hamzatazib** [comment]
Hi @minty99 
Unfortunately danger_map is a private repository because it also contains some proprietary data used by the website and we cannot publicize it. On the other hand, the master branch is from time to time (usually once a week) updated with processed files (in data/processed) so you should be able to have access to the Cases_... files you need to run the main scripts. Be careful as the structure is not exactly the same as in danger_map and we apologize about that. We will try to make as many resources as possible public as time goes by.
Hamza
