### ISSUE TITLE
Does your model provide confidence interval for predictions?

### ISSUE THREAD

**Issue by YuqiZ2020** [COVIDAnalytics/DELPHI#50]
Hello,

I think the predictions that are available on CDC show that your model provides confidence intervals for the predictions. Is the code for confidence intervals available on GitHub?  

Thank you in advance!

Yuqi

**Comment by MichaelLLi** [comment]
Hi Yuqi:

Thanks for the info. The code for the CDC predictions is in a separate folder, and thus we haven't made them available. However, our method of calculating confidence intervals is very simple and you should be able to implement it easily.

Since our model is not a Bayesian-type model, we can only estimate our confidence intervals through a noise structure. In particular, we take our historical predictions (usually from 2 weeks ago), and measure the RMSE for the daily cases and deaths in the out-of-sample period (e.g. 2 weeks). 

Then we assume that going forward, the noise for daily cases and deaths are distributed as a Normal distribution with mean 0 and standard deviation  the RMSE for the daily cases/deaths. Therefore, for a prediction made for k days ahead, the noise is normally distributed as standard deviation sqrt(k) * RMSE for the daily cases/deaths. Using this, one can easily calculate confidence intervals using just the normal quantiles.

We will be updating the website and this repository in a few days to include the code for confidence intervals, as part of a larger change. In the mean time, if you want to see for an example on how the code is done, you can go to the delphi_improvements branch of the codebase, and look at DELPHI_utils_V3.py. In there, there is a function create_datasets_with_confidence_intervals that includes code on creating confidence intervals, ans is consistent with our code for the CDC.

Best
-Michael Li

**Comment by YuqiZ2020** [comment]
Hi Michael, 

Sounds good, thank you so much!

Best,
Yuqi
